# Generated by Django 5.0.1 on 2024-01-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0003_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sulg',
            field=models.SlugField(default=''),
        ),
    ]
