# Generated by Django 5.0.1 on 2024-01-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_book_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sulg',
            new_name='slug',
        ),
    ]
